In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits import mplot3d
import sys
import PIL
import os
from sklearn.datasets import load_digits
from sklearn.manifold import MDS
from sklearn.model_selection import train_test_split
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
import seaborn as sns
import umap.umap_ as umap

%matplotlib inline

In [2]:
# extracting image data
images = np.load('data.npy')
print(images.shape)


(243, 2985984)


In [4]:
# extracting label data
with open('labels.txt') as f:
    labels = f.readlines()
for i in range(len(labels)):
    labels[i] = labels[i][:-1]
print(len(labels))


243


In [5]:
# Multidimensional scaling
mds = MDS(n_components=3)
images_MDS = mds.fit_transform(images)
images_MDS.shape

(243, 3)

In [6]:
print(images_MDS)
print(type(images_MDS))
np.save('MDS_points.npy', images_MDS)


[[-2.36413807e+01 -7.97620107e+01 -3.11784029e+02]
 [-1.83818136e+01 -1.25991699e+02  2.47243874e+02]
 [-5.13329338e+01  2.27765343e+02 -1.39249785e+02]
 [-3.30692675e+01 -5.73870904e+01  7.55945620e+00]
 [-1.70872078e+02 -1.23098174e+02 -5.03127496e+01]
 [ 7.94203477e+01 -1.70104900e+02 -4.36099101e+01]
 [-9.51117427e+01 -1.82075622e+02  3.84678414e+01]
 [-6.44247263e+01  2.47993395e+01  6.14580756e+01]
 [ 1.32412625e+02  9.14216530e+01  3.29655591e+02]
 [-1.70629571e+01 -1.61481453e+01  3.06440530e+02]
 [-2.12868628e+01 -7.78860490e+01  5.28007233e+01]
 [-1.22634998e+02  7.99194640e+01  1.81012952e+02]
 [-1.66747275e+02  2.91471384e+01 -1.29532929e+02]
 [ 1.67191686e+01  1.67069091e+02 -6.51063555e+01]
 [-1.37580816e+01  4.19494050e+01  4.82096960e+01]
 [-9.12544866e+01 -1.51930650e+01 -5.87040272e+01]
 [-4.19210765e+01 -5.74893162e+01  4.76365031e+01]
 [ 1.06890233e+02 -1.39254905e+02  2.18886312e+02]
 [-1.36608402e+01 -1.51534345e+01 -1.39357202e+00]
 [-6.03205100e+01  2.62177429e+

In [7]:
# Principal Component Analysis (currently kernel dies on 16GB of RAM)
pca = PCA(n_components=3)

In [ ]:
principalComponents = pca.fit_transform(images)
print(principalComponents)

In [ ]:
# Uniform Manifold Approximation & Projection
fit = umap.UMAP(n_components=3)
%time u = fit.fit_transform(images)

In [ ]:
print(u)